### PR TITLE
shutdown Mongo on unmock

### PR DESCRIPTION
**Pull request by pibi**
Actually mongodb-prebuilt is still active until the node process dies, even if it was unmocked. 

This patch force a shutdown on unmock, killing the mongodb-prebuilt process.
It needs https://github.com/winfinit/mongodb-prebuilt/pull/28 to work

### CODE REVIEW

**Comment by pibi** [comment]
@winfinit, please check this fix, it solve a big performance issue when mockgoose is used for unit tests (actually mockgoose starts one mongodb-prebuilt process for every test. These processes are left in memory until the node test process dies)

**Comment by pibi** [comment]
```
1) User functions unmock:
     TypeError: mongod.shutdown is not a function
      at Mockgoose.js:171:20
      at Mongoose.mongoose.unmock (Mockgoose.js:167:18)
      at Context.<anonymous> (test/index.js:51:11)
```

CI tests failed due to https://github.com/winfinit/mongodb-prebuilt/pull/28

**Comment by pibi** [comment]
@winfinit: is there any chance to merge this?
